name: Update flakes

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  upgrade:
    permissions:
      contents: write
      
    name: Upgrade
    
    runs-on: ubuntu-22.04
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
        
      - name: Flake update nixpkgs
        run: nix flake update github:nixos/nixpkgs/nixos-23.05

      - name: Flake update nixpkgs-unstable
        run: nix flake update github:nixos/nixpkgs/nixos-unstable
        
      - name: Flake update nixpkgs-master
        run: nix flake update github:nixos/nixpkgs/master
      
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.3
        with:
          message: "Update flake.lock file"
